
LibName=LibSndMDX

include ../makefile_before.mak

# ----------------------------------------------------------------------------------
OBJS+= $(LibName).o
intlib=mdxplay-20070206
OBJS+= $(intlib)/mdx2151.o $(intlib)/mdxfile.o $(intlib)/mdxmml_ym2151.o $(intlib)/pcm8.o $(intlib)/pdxfile.o $(intlib)/ym2151.o

include ../makefile_after.mak

