
LibName=LibSndTTA

include ../makefile_before.mak

# ----------------------------------------------------------------------------------
OBJS+= $(LibName).o
intlib=ttalib-hwplayer-1.2
OBJS+= $(intlib)/ttadec.o

include ../makefile_after.mak

