
LibName=LibImgJpeg

include ../makefile_before.mak

# ----------------------------------------------------------------------------------
OBJS+= $(LibName).o
intlib=jpegsr8c
OBJS+= $(intlib)/jaricom.o $(intlib)/jcomapi.o $(intlib)/jdapimin.o $(intlib)/jdapistd.o $(intlib)/jdarith.o $(intlib)/jdatadst.o $(intlib)/jdatasrc.o $(intlib)/jdcoefct.o $(intlib)/jdcolor.o $(intlib)/jddctmgr.o $(intlib)/jdhuff.o $(intlib)/jdinput.o $(intlib)/jdmainct.o $(intlib)/jdmarker.o $(intlib)/jdmaster.o $(intlib)/jdmerge.o $(intlib)/jdpostct.o $(intlib)/jdsample.o $(intlib)/jdtrans.o $(intlib)/jerror.o $(intlib)/jidctfst.o $(intlib)/jidctint.o $(intlib)/jmemansi.o $(intlib)/jmemmgr.o $(intlib)/jquant1.o $(intlib)/jutils.o

include ../makefile_after.mak

