
LibName=LibSndMIDI

include ../makefile_before.mak

# ----------------------------------------------------------------------------------
OBJS+= $(LibName).o
intlib=midiemu
OBJS+= $(intlib)/mtrk.o $(intlib)/pch.o $(intlib)/rcplib.o $(intlib)/smidlib.o $(intlib)/smidlib_sm.o $(intlib)/sndfont.o

include ../makefile_after.mak

