
LibName=libzlib

include ../makefile_before.mak

# ----------------------------------------------------------------------------------
OBJS+= 
zlib=zlib-1.2.5
OBJS+= $(zlib)/adler32.o $(zlib)/crc32.o $(zlib)/deflate.o $(zlib)/gzclose.o $(zlib)/gzlib.o $(zlib)/gzread.o $(zlib)/gzwrite.o $(zlib)/infback.o $(zlib)/inffast.o $(zlib)/inflate.o $(zlib)/inftrees.o $(zlib)/trees.o $(zlib)/zutil.o

include ../makefile_after.mak

