
LibName=LibSndG721

include ../makefile_before.mak

# ----------------------------------------------------------------------------------
OBJS+= $(LibName).o
intlib=g721dec
OBJS+= $(intlib)/g721dec.o

include ../makefile_after.mak

