
LibName=LibImgPNG

include ../makefile_before.mak

# ----------------------------------------------------------------------------------
OBJS+= $(LibName).o
intlib=libpng155
OBJS+= $(intlib)/png.o $(intlib)/pngerror.o $(intlib)/pngget.o $(intlib)/pngmem.o $(intlib)/pngpread.o $(intlib)/pngread.o $(intlib)/pngrio.o $(intlib)/pngrtran.o $(intlib)/pngrutil.o $(intlib)/pngset.o $(intlib)/pngtrans.o

include ../makefile_after.mak

